### ISSUE TITLE
Additional Education Materiel Request 

### ISSUE THREAD

**Issue by GProtoZeroW** [jordens/rayopt-notebooks#2]
Sorry, my optics education was garbage and this look to be an awesome optics tool that I am hoping is very viable to the commercial one. With that said can you add a notebook on what all the graphs that `Analysis` produces and how to add them to custom graph/ extract the analysis results for more processing. 

Also, I am wondering if rayopt can extract a consolidated Ray Tracing matrix for use in the fractional Fourier transform for optics (see: https://www.researchgate.net/publication/230914046_Teaching_Fourier_optics_through_ray_matrices), as well as a low order impulse function/transfer function to then, use in image processing 

Anyways; awesome library that existing tutorials really help show off.

**Comment by jordens** [comment]
The graphs in `Analysis` are modeled and named after the usual nomenclature of Oslo/Zemax and optical design literature. E.g. the [transverse plots](https://github.com/quartiq/rayopt/blob/318586a0103805a49cbf177d434f6bddf66122d3/rayopt/analysis.py#L222-L248). Pull requests with more documentation or would be welcome. Modularization seems difficult in this case and probably not worth it.

`ParaxialTrace` and `GaussianTrace` both use and implement first order optics as in the paper you mention. You can use the matrix from them. But since this is only first order optics (also in the paper) the use for image processing is per definition pretty limited.
